"""Rewrite arduino/FlushFan/mfe_tables.h from features.py. Only needed if MFE constants change."""

from __future__ import annotations

from pathlib import Path

from features import FILTERBANK, N_FFT, N_FFT_BINS, N_MELS, WINDOW, sparse_filterbank

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "arduino" / "FlushFan" / "mfe_tables.h"


def c_float_array(name: str, values, cols: int = 8) -> str:
    parts = [f"{float(v):.8f}f" for v in values]
    lines = [f"const float {name}[{len(parts)}] = {{"]
    for i in range(0, len(parts), cols):
        chunk = ", ".join(parts[i : i + cols])
        comma = "," if i + cols < len(parts) else ""
        lines.append(f"  {chunk}{comma}")
    lines.append("};")
    return "\n".join(lines)


def c_int16_array(name: str, values) -> str:
    parts = [str(int(v)) for v in values]
    return f"const int16_t {name}[{len(parts)}] = {{ {', '.join(parts)} }};"


def main() -> None:
    starts, lengths, weights, offsets = sparse_filterbank()
    body = "\n".join(
        [
            "// Auto-generated by generate_tables.py — do not edit.",
            "#pragma once",
            "#include <stdint.h>",
            "",
            f"constexpr int kNFft = {N_FFT};",
            f"constexpr int kNFftBins = {N_FFT_BINS};",
            f"constexpr int kNWeights = {len(weights)};",
            "",
            c_float_array("kHannWindow", WINDOW, 8),
            "",
            c_int16_array("kMelStart", starts),
            c_int16_array("kMelLength", lengths),
            c_int16_array("kMelWeightOffset", offsets),
            "",
            c_float_array("kMelWeights", weights, 6),
            "",
        ]
    )
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(body + "\n", encoding="utf-8")
    print(f"Wrote {OUT} ({OUT.stat().st_size} bytes, {len(weights)} packed weights)")


if __name__ == "__main__":
    main()
